services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flashdeal
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mysql-data:
